# -*- coding: utf-8 -*-
"""PalmerPenguinsM5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eul0NaSnStbGJZXs9X0yquWFdiw05iGW
"""

# Palmer Penguins
# Raynette Brown
# 10.04.2026
# Uses loops to repeatedly explore Palmer Penguins statistics

import math #Import the math module

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

# add constants for the number of penguins
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

# List of species Names
species_names = [SP_CHINSTRAP, SP_GENTOO,SP_ADELIE]

#Species Counts
species_counts = [NUM_CHINSTRAP,NUM_GENTOO,NUM_ADELIE]

#Determine number of species using len()
total_species = len(species_names)

# Calculate total penguins
total_penguins = sum(species_counts)

# Average Penguins Stats
average_penguins = total_penguins / total_species
average_penguins_rouneded_up = math.ceil(average_penguins)

#Calculate the species percentages using list indexes
chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

# Find largest and smallest species
largest_count = max(species_counts)
smallest_count = min(species_counts)
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]

# List of species percentages
species_percentages = [chinstrap_percent, gentoo_percent,adelie_percent]

# output the species names with introductory text

print("Introducing the Palmer Penguins")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()

print(f"There are a total of {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is "
      f"{average_penguins:.1f}.")
print(f"The avergage number of penguins rounded up is {average_penguins_rouneded_up}.")
print()
#Display species statistics using a for loop
for index, species in enumerate(species_names):
    print(f"{species}: {species_counts[index]} "
          f"({species_percentages[index]:.2f}%)")
print()
print(f"The species with the most observations is {largest_species} with {largest_count} penguins.")
print(f"The species with the fewest observations is {smallest_species} with {smallest_count} penguins.")

# prompt the user to select a species
print()
valid_selections = 0
print("Explore a species")
species_choice = input (
    "Enter Chinstrap, Gentoo, or Adelie, or Done: ")

# Continue exploring species until the user enters Done
while species_choice != "Done":
    # Validate species selection
    if species_choice not in species_names:
        print(species_choice +
              " is not one of the species in this dataset")
    else:
        valid_selections += 1
        # Determine the selected speces:
        species_choice = input(
            "Enter Chinstrap, Gentoo, Adelie, or Done:")
    # Classify the selected species
    selected_species = species_names[selected_index]
    selected_count = species_counts[selected_index]
    selected_percent = species_percentages[selected_index]

    # Classify the selected species by percent
    if selected_percent < 25:
        size_category = "small"
    elif selected_percent < 40:
        size_category = "medium"
    else:
        size_category = "large"

    # Species position
    if selected_species == largest_species:
            position_description = "largest"
    elif selected_species == smallest_species:
            position_description = "smallest"
    else:
        position_description = "middle-sized"

    # Selected species count by average
    average_position = ("above" if selected_count > average_penguins else "below")

    #Display the selected species stats
    print()
    print(f"{selected_species} has {selected_count} observations, "
              f"representing {selected_percent:.2f}% of the dataset.")
    print(f"{selected_species} is classified as a "
              f"{size_category} species group.")
    print(f"{selected_species} is the {position_description} "
              f"species group.")
    print(f"Its observation count is {average_position} "
              f"the dataset average of {average_penguins:.1f}.")
    # Ask for another species
    print()
    species_choice = input("Enter Chinstrap, Gentoo, Adelie, or Done: ")

    print()
    print(f"You explored {valid_selections} valid species.")
    print("Exploration complete.")